# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /opt/mealie/data:z
    io.containers.autoupdate/mealie-api: registry docker.io/hkotel/mealie:api-nightly
    io.containers.autoupdate/mealie-frontend: registry docker.io/hkotel/mealie:frontend-nightly
  creationTimestamp: "2023-09-21T16:13:20Z"
  labels:
    app: mealie
  name: mealie
spec:
  containers:
  - env:
    - name: WEB_GUNICORN
      value: "true"
      # change BASE_URL
    - name: BASE_URL
      value: http://food.home.localhost
    - name: MAX_WORKERS
      value: "1"
    - name: ALLOW_SIGNUP
      value: "false"
    - name: WEB_CONCURRENCY
      value: "1"
    image: docker.io/hkotel/mealie:api-nightly
    name: mealie-api
    ports:
    - containerPort: 3000
      hostPort: 10006
    volumeMounts:
    - mountPath: /app/data
      name: opt-mealie-data-host-0
  - env:
    - name: API_URL
      value: http://mealie-api:9000
    image: docker.io/hkotel/mealie:frontend-nightly
    name: mealie-frontend
    volumeMounts:
    - mountPath: /app/data
      name: opt-mealie-data-host-0
  volumes:
  - hostPath:
      path: /opt/mealie/data
      type: Directory
    name: opt-mealie-data-host-0
