# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-10-11T15:05:55Z"
  labels:
    app: mealie
  name: mealie
spec:
  containers:
  - env:
    - name: BASE_URL
      value: http://mealie.foo.com
    - name: MAX_WORKERS
      value: "1"
    - name: WEB_CONCURRENCY
      value: "1"
    - name: TZ
      value: America/Winnipeg
    - name: ALLOW_SIGNUP
      value: "true"
    image: docker.io/hkotel/mealie:api-v1.0.0beta-5
    name: mealie-api
    ports:
    - containerPort: 3000
      hostPort: 10006
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/data
      name: opt-mealie-data-host-0
  - env:
    - name: API_URL
      value: http://mealie-api:9000
    image: docker.io/hkotel/mealie:frontend-v1.0.0beta-5
    name: mealie-frontend
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/data
      name: opt-mealie-data-host-0
  hostname: mealie
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /opt/mealie/data
      type: Directory
    name: opt-mealie-data-host-0
status: {}

