# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.7

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/srv/containers/heimdall: Z
    io.containers.autoupdate/heimdall: registry:w
  creationTimestamp: "2022-05-05T02:31:49Z"
  labels:
    app: heimdall
  name: heimdall
spec:
  containers:
  - image: docker.io/linuxserver/heimdall:latest
    name: heimdall
    ports:
    - containerPort: 80
      hostPort: 10000
    - containerPort: 443
      hostPort: 10443
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: srv-containers-heimdall-host-0
  volumes:
  - hostPath:
      path: /srv/containers/heimdall
      type: Directory
    name: srv-containers-heimdall-host-0
