# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /opt/authentik/custom-templates:z
    io.containers.autoupdate/authentik-db: registry
    io.containers.autoupdate/authentik-ldap: registry
    io.containers.autoupdate/authentik-redis: registry
    io.containers.autoupdate/authentik-server: registry
    io.containers.autoupdate/authentik-worker: registry
  creationTimestamp: "2023-10-02T15:39:50Z"
  labels:
    app: authentik
  name: authentik
spec:
  containers:
  - args:
    - redis-server
    image: docker.io/library/redis:alpine
    name: authentik-redis
    ports:
    - containerPort: 9000
      hostPort: 9000
    - containerPort: 9443
      hostPort: 9443
    volumeMounts:
    - mountPath: /data
      name: b8d67f3cb3168ec47fd5a573fa3a1d0fcc97fa9b98296c12b1eb71266263f8b3-pvc
  - args:
    - postgres
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_USER
      value: authentik
    - name: POSTGRES_PASSWORD
      value: IrXI1iozo72RBjEPNqTKMmeIa0E97nomX2agQSH0
    image: docker.io/library/postgres:14-alpine
    name: authentik-db
    volumeMounts:
    - mountPath: /var/lib/postgresql/data/pgdata
      name: opt-authentik-db-host-0
    - mountPath: /var/lib/postgresql/data
      name: 50732094dabc51136c13d532e083d29d84e74dd62b84fc337c0575a08f2f5f1d-pvc
  - args:
    - server
    env:
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      value: IrXI1iozo72RBjEPNqTKMmeIa0E97nomX2agQSH0
    - name: AUTHENTIK_SECRET_KEY
      value: SDCdtYtaHnlAzSr63fTIASYqqOfDQlNtECPIzFx1969JqdhO6A
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: 127.0.0.1
    - name: AUTHENTIK_REDIS__HOST
      value: 127.0.0.1
    image: ghcr.io/goauthentik/server:latest
    name: authentik-server
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /media
      name: opt-authentik-media-host-0
    - mountPath: /templates
      name: opt-authentik-custom-templates-host-1
  - args:
    - worker
    env:
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      value: IrXI1iozo72RBjEPNqTKMmeIa0E97nomX2agQSH0
    - name: AUTHENTIK_SECRET_KEY
      value: SDCdtYtaHnlAzSr63fTIASYqqOfDQlNtECPIzFx1969JqdhO6A
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_REDIS__HOST
      value: 127.0.0.1
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: 127.0.0.1
    image: ghcr.io/goauthentik/server:latest
    name: authentik-worker
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /backups
      name: opt-authentik-backups-host-0
    - mountPath: /media
      name: opt-authentik-media-host-1
    - mountPath: /templates
      name: opt-authentik-custom-templates-host-2
  - env:
    - name: AUTHENTIK_HOST
      value: https://sso.domain.ltd
    - name: AUTHENTIK_INSECURE
      value: "false"
    - name: AUTHENTIK_TOKEN
      value: TOKEN
    image: ghcr.io/goauthentik/ldap:latest
    name: authentik-ldap
    securityContext:
      runAsNonRoot: true
  volumes:
  - name: 50732094dabc51136c13d532e083d29d84e74dd62b84fc337c0575a08f2f5f1d-pvc
    persistentVolumeClaim:
      claimName: 50732094dabc51136c13d532e083d29d84e74dd62b84fc337c0575a08f2f5f1d
  - hostPath:
      path: /opt/authentik/media
      type: Directory
    name: opt-authentik-media-host-0
  - hostPath:
      path: /opt/authentik/custom-templates
      type: Directory
    name: opt-authentik-custom-templates-host-1
  - hostPath:
      path: /opt/authentik/backups
      type: Directory
    name: opt-authentik-backups-host-0
  - hostPath:
      path: /opt/authentik/media
      type: Directory
    name: opt-authentik-media-host-1
  - hostPath:
      path: /opt/authentik/custom-templates
      type: Directory
    name: opt-authentik-custom-templates-host-2
  - name: b8d67f3cb3168ec47fd5a573fa3a1d0fcc97fa9b98296c12b1eb71266263f8b3-pvc
    persistentVolumeClaim:
      claimName: b8d67f3cb3168ec47fd5a573fa3a1d0fcc97fa9b98296c12b1eb71266263f8b3
  - hostPath:
      path: /opt/authentik/db
      type: Directory
    name: opt-authentik-db-host-0
