# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.1.0
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/opt/jupyter: z
    bind-mount-options:/opt/jupyter/jupyter-app: z
    io.containers.autoupdate/jupyter-app: registry
    io.containers.autoupdate/jupyter/jupyter-app: registry
    io.kubernetes.cri-o.ContainerType/jupyter-app: container
    io.kubernetes.cri-o.SandboxID/jupyter-app: 2a7ec0475b87cc3b932365b695b67510c28fa971a0f83e7a54713851b30ee1b
    io.podman.annotations.autoremove/jupyter-app: "FALSE"
    io.podman.annotations.init/jupyter-app: "FALSE"
    io.podman.annotations.privileged/jupyter-app: "FALSE"
    io.podman.annotations.publish-all/jupyter-app: "FALSE"
  creationTimestamp: "2022-05-29T15:37:35Z"
  labels:
    app: jupyter
  name: jupyter
spec:
  containers:
  - args:
    - start-notebook.sh
    - --NotebookApp.token=
    image: docker.io/jupyter/scipy-notebook:latest
    name: jupyter-app
    ports:
    - containerPort: 8888
      hostPort: 10001
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /home/jovyan/work
      name: opt-jupyter-host-0
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /opt/jupyter
      type: Directory
    name: opt-jupyter-host-0
status: {}
