# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/opt/jupyter/jupyter-app/jupyter-lab: z
    bind-mount-options:/opt/jupyter/jupyter-lab: z
    io.containers.autoupdate/jupyter-app/jupyter-lab: registry
    io.containers.autoupdate/jupyter/jupyter-app/jupyter-lab: registry
    io.kubernetes.cri-o.ContainerType/jupyter-app/jupyter-lab: container
    io.kubernetes.cri-o.SandboxID/jupyter-app/jupyter-lab: 2a7ec0475b87cc3b932365b695b67510c28fa971a0f83e7a54713851b30ee1b
    io.podman.annotations.autoremove/jupyter-app/jupyter-lab: "FALSE"
    io.podman.annotations.init/jupyter-app/jupyter-lab: "FALSE"
    io.podman.annotations.privileged/jupyter-app/jupyter-lab: "FALSE"
    io.podman.annotations.publish-all/jupyter-app/jupyter-lab: "FALSE"
  creationTimestamp: "2023-02-23T17:47:41Z"
  labels:
    app: jupyter
  name: jupyter
spec:
  containers:
  - args:
    - start-notebook.sh
    - --NotebookApp.token=
    image: docker.io/jupyter/scipy-notebook:latest
    name: lab
    ports:
    - containerPort: 8888
      hostPort: 10001
    resources: {}
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /home/jovyan/
      name: opt-jupyter-host-0
  hostname: jupyter
  restartPolicy: Unless-stopped
  volumes:
  - hostPath:
      path: /opt/jupyter
      type: Directory
    name: opt-jupyter-host-0
status: {}

