# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.7

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/opt/jupyter: z
    io.containers.autoupdate/jupyter: registry
  creationTimestamp: "2022-05-05T02:28:58Z"
  labels:
    app: jupyter
  name: jupyter
spec:
  containers:
  - args:
    - start-notebook.sh
    - --NotebookApp.token=
    image: docker.io/jupyter/scipy-notebook:latest
    name: jupyter
    ports:
    - containerPort: 8888
      hostPort: 10001
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /home/jovyan/work
      name: opt-jupyter-host-0
  volumes:
  - hostPath:
      path: /opt/jupyter
      type: Directory
    name: opt-jupyter-host-0
