# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.7

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/opt/valheim/config: z
    bind-mount-options:/opt/valheim/data: z
    io.containers.autoupdate/valheim: registry
  creationTimestamp: "2022-05-05T02:35:05Z"
  labels:
    app: valheim
  name: valheim
spec:
  containers:
  - image: docker.io/lloesche/valheim-server:latest
    name: valheim
    ports:
    - containerPort: 2456
      hostPort: 2456
      protocol: UDP
    - containerPort: 2457
      hostPort: 2457
      protocol: UDP
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: opt-valheim-config-host-0
    - mountPath: /opt/valheim
      name: opt-valheim-data-host-1
  volumes:
  - hostPath:
      path: /opt/valheim/config
      type: Directory
    name: opt-valheim-config-host-0
  - hostPath:
      path: /opt/valheim/data
      type: Directory
    name: opt-valheim-data-host-1
