# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.7

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/opt/mealie/data: Z
    io.containers.autoupdate/mealie: registry
  creationTimestamp: "2022-05-05T04:40:35Z"
  labels:
    app: mealie
  name: mealie
spec:
  containers:
  - image: docker.io/hkotel/mealie:latest
    name: mealie
    ports:
    - containerPort: 80
      hostPort: 10006
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/data/
      name: opt-mealie-data-host-0
  volumes:
  - hostPath:
      path: /opt/mealie/data
      type: Directory
    name: opt-mealie-data-host-0
